
TDB-LOG-TBILL : 
 id : tbtdb
 pwd : tbtdb
 url : # FIXME
 database : LOG
 table : TBILL
 driver : com.mysql.jdbc.Driver
TdbSession : 
 id : tbtdb
 pwd : tbtdb
 database : TX
 table : TSESSION
 url : # FIXME
 driver : com.mysql.jdbc.Driver
LgLogProtocol : 
 id : lpy
 pwd : tblpy
 database : LOG
 table : TB_LPY_PROTOCOL
 url : # FIXME
 driver : com.mysql.jdbc.Driver