
Test Folder Path : C:\Users\homesking\Desktop\Test Helper\테스트 케이스
Yaml Editor : C:\Users\homesking\AppData\Local\Programs\Microsoft VS Code\Code.exe
Log : 
 size : 15px;
 background : black;
 word : 
  Response : GREEN
  TXTYPE : BLUE
  Request : GREEN
  COMMAND : BLUE
  TID : rgb(255, 255, 77)
  FAIL : rgb(255, 0, 0)